### PR TITLE
find CITATION if inst/CITATION does not exist

### LINKED ISSUE #3: CITATION is not parsed for installed packages
`write_codemeta()` does not parse CITATION for installed packages.

``` r
library(codemeta)
pkg_path <- find.package("jsonlite")
tf <- tempfile()
cm <- write_codemeta(pkg_path, tf)
cm$citation
#> NULL
file.exists(system.file("CITATION", package = "jsonlite"))
#> [1] TRUE
```

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.1.1 (2021-08-10)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language en                          
#>  collate  German_Germany.1252         
#>  ctype    German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2021-08-20                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source             
#>  backports     1.2.1   2020-12-09 [1] standard (@1.2.1)  
#>  cli           3.0.1   2021-07-17 [1] standard (@3.0.1)  
#>  codemeta    * 0.1.0   2021-07-22 [1] standard (@0.1.0)  
#>  crayon        1.4.1   2021-02-08 [1] standard (@1.4.1)  
#>  desc          1.3.0   2021-03-05 [1] standard (@1.3.0)  
#>  digest        0.6.27  2020-10-24 [1] standard (@0.6.27) 
#>  ellipsis      0.3.2   2021-04-29 [1] standard (@0.3.2)  
#>  evaluate      0.14    2019-05-28 [1] standard (@0.14)   
#>  fansi         0.5.0   2021-05-25 [1] standard (@0.5.0)  
#>  fs            1.5.0   2020-07-31 [1] standard (@1.5.0)  
#>  glue          1.4.2   2020-08-27 [1] standard (@1.4.2)  
#>  highr         0.9     2021-04-16 [1] standard (@0.9)    
#>  htmltools     0.5.1.1 2021-01-22 [1] standard (@0.5.1.1)
#>  jsonlite      1.7.2   2020-12-09 [1] standard (@1.7.2)  
#>  knitr         1.33    2021-04-24 [1] standard (@1.33)   
#>  lifecycle     1.0.0   2021-02-15 [1] standard (@1.0.0)  
#>  magrittr      2.0.1   2020-11-17 [1] standard (@2.0.1)  
#>  pillar        1.6.2   2021-07-29 [1] standard (@1.6.2)  
#>  pkgconfig     2.0.3   2019-09-22 [1] standard (@2.0.3)  
#>  purrr         0.3.4   2020-04-17 [1] standard (@0.3.4)  
#>  R6            2.5.1   2021-08-19 [1] standard (@2.5.1)  
#>  reprex        2.0.1   2021-08-05 [1] standard (@2.0.1)  
#>  rlang         0.4.11  2021-04-30 [1] standard (@0.4.11) 
#>  rmarkdown     2.10    2021-08-06 [1] standard (@2.10)   
#>  rprojroot     2.0.2   2020-11-15 [1] standard (@2.0.2)  
#>  rstudioapi    0.13    2020-11-12 [1] standard (@0.13)   
#>  sessioninfo   1.1.1   2018-11-05 [1] standard (@1.1.1)  
#>  stringi       1.7.3   2021-07-16 [1] standard (@1.7.3)  
#>  stringr       1.4.0   2019-02-10 [1] standard (@1.4.0)  
#>  styler        1.5.1   2021-07-13 [1] standard (@1.5.1)  
#>  tibble        3.1.3   2021-07-23 [1] standard (@3.1.3)  
#>  utf8          1.2.2   2021-07-24 [1] standard (@1.2.2)  
#>  vctrs         0.3.8   2021-04-29 [1] standard (@0.3.8)  
#>  withr         2.4.2   2021-04-18 [1] standard (@2.4.2)  
#>  xfun          0.25    2021-08-06 [1] standard (@0.25)   
#>  yaml          2.2.1   2020-02-01 [1] standard (@2.2.1)  
#> 
#> [1] C:/Users/Daniel.AK-HAMBURG/Documents/R/win-library/4.1
#> [2] C:/Program Files/R/R-4.1.1/library
```

</details>

### PR DESCRIPTION
**Pull request by dpprdan**
`guess_citation()` now finds CITATION if inst/CITATION does not exist. 
It handles both source and installed packages by path (not by name - or did I miss something why that is necessary?). 

fixes #3

### CODE REVIEW

**Comment by cboettig** [comment]
Thanks!  Can you add a unit test that will cover this case too?

`codemeta` basically follows existing conventions in `devtools` and `usethis` and similar developer-centric tools that operate based on path rather than package name, and assume the developer is working in the source repo and not the installed package.  `codemetar` overloaded it's functions to support both installed and developer packages (and I think could work using the name of an installed package rather than the path), but in retrospect I'm not convinced that overloading was really a good design.   Feedback / input welcome always.

**Comment by dpprdan** [comment]
re. unit test: There is only one unit test at the moment which doesn't test citation. Is it okay, if I take the relevant tests/files from codemetar for this and adjust accordingly?

name vs. path: I don't feel that I have a full grasp of the {codemeta(r)} code yet nor do I know all intended use-cases. With that caveat in mind these are my random thoughts on the topic: 

1. It's easy to get the path of an installed package with `find.package("package")` and pass that to {codemeta} functions.
2. Creating codemeta.json files makes most sense for in-development packages. Or rather I don't see a common use case for installed-only packages. I might be wrong, though? (In any case codemeta should keep supporting installed packages IMHO, since it makes examples, reprexes and so forth easier.)
3. While it is easy to get the path of an installed package (see 1.), it is not so easy to cover every corner case/prevent unnecessary issues when trying to support both name and path. I was wondering for example whether `is_installed()` could be problematic in the (IMO) not very uncommon situation where you are working on a source package while having it also installed - probably a previous version though. I haven't tested it however.

So from what I've seen/understood so far, I'd agree that codemeta should support path only.

**Comment by cboettig** [comment]
yup, sounds good!  if you can just add the extra test I'll go ahead and merge

**Comment by dpprdan** [comment]
@cboettig I've adapted some tests from {codemetar} re. citation. It is a bit more convoluted than I'd like, but it turns that testing for whether `inst/CITATION` and `CITATION` are actually found is not straight forward, given that `R CMD check` always complains if `CITATION` is anywhere other than in `inst/`. So the CITATION file to test against cannot be named CITATION... Please let me know if you're aware of a better way to do this. (Maybe using {withr} would get rid of a line or two, but at the cost of a (soft) dependency on {withr}).

I have put the examples to test against inside the test folder instead of `inst/examples` because they are only used for tests and not for as examples (this should result in a slightly smaller package size IIUC).

**Comment by cboettig** [comment]
ha, that's a bit aggressive of `R CMD check`!  Hmm, I might consider checking for the `citation` of an installed dependency like `jsonlite`; but his looks perfectly fine to me!

**Comment by dpprdan** [comment]
I thought about jsonlite (or any other dependency), but decided against it due to the (admittedly tiny) chance that Jeroen might change the (`@type` of) CITATION. In other words, this way we control the file we test against. 🤷🏻‍♂️

**Comment by cboettig** [comment]
excellent point!

**Pull request merged**
