### PR TITLE
Update GHA workflows

### PR DESCRIPTION
**Pull request by maelle**
I saw a failure of the current workflow and thought this might help?

### CODE REVIEW

**Comment by cboettig** [comment]
hmm, Windows has some UTF-8 objections here..... Any ideas?

**Comment by maelle** [comment]
I suspect that writing my first name to a snapshot is not a good idea :joy: I'm looking into where the encoding is problematic.

**Comment by maelle** [comment]
https://github.com/r-lib/testthat/issues/1574

**Comment by maelle** [comment]
In the meantime I'd suggest a `skip_on_windows()`?

**Comment by maelle** [comment]
we should skip for R < 4.2

**Pull request closed without merging**
